# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arrayC <- function(input, dim) {
    .Call(`_hello_R_arrayC`, input, dim)
}

arr3d <- function(forcing_3d, soil_par_mat, forcing_veg_list) {
    invisible(.Call(`_hello_R_arr3d`, forcing_3d, soil_par_mat, forcing_veg_list))
}

